# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

ENV["LC_ALL"] = "en_US.UTF-8"

n_nodes = 5

Vagrant.configure("2") do |config|

  (1..n_nodes).each do |i|
    config.vm.define "c#{'%02d' % i}" do |host|
      host.vm.box = "ubuntu/xenial64"
      host.vm.hostname = "c#{'%02d' % i}"
      host.vm.network "public_network", ip: "192.168.0.5#{i}"
      #host.vm.network "private_network", ip: "10.0.0.#{i}"
      host.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.cpus = 4
        vb.memory = "16384"
      end
      host.disksize.size = '64GB'
      host.vm.synced_folder "../../../", "/home/vagrant/st-kilda-pier", owner: "vagrant", group: "vagrant"
    end
  end

end
