---
- hosts: all
  tasks:
  - name: /etc/hosts
    become: yes
    lineinfile:
      path: "/etc/hosts"
      line: "{{ hostvars[item].ansible_host }} {{ hostvars[item].inventory_hostname }}"
      state: absent
    with_items: "{{ groups['all'] }}"

...