---
- hosts: all
  strategy: free
  vars:
    home: "{{ lookup('env', 'HOME') }}"
    user: "{{ lookup('env', 'USER') }}"
    pri_key: "{{ home }}/.ssh/id_rsa"
    pub_key: "{{ lookup('file', '{{ home }}/.ssh/id_rsa.pub') }}"
  tasks:
  - name: debug
    debug:
      msg: >
        "home: {{ home }},
        user: {{ user }},
        pri_key: {{ pri_key }},
        pub_key: {{ pub_key }},
        ansible_env: {{ ansible_env }}"
    tags:
    - debug
  - name: /etc/sudoers
    become: yes
    lineinfile:
      path: "/etc/sudoers"
      line: "{{ user }} ALL=(ALL) NOPASSWD:ALL"
      validate: "/usr/sbin/visudo -cf %s"
  - name: /etc/hosts
    become: yes
    lineinfile:
      path: "/etc/hosts"
      line: "{{ hostvars[item].ansible_host }} {{ hostvars[item].inventory_hostname }}"
    with_items: "{{ groups['all'] }}"
  - name: openssh_keypair
    openssh_keypair:
      path: "{{ pri_key }}"
  - name: authorized_key
    authorized_key:
      user: "{{ user }}"
      state: present
      key: "{{ pub_key }}"    

...