---
- name: sudoers
  import_playbook: sudoers_add.yml 

- name: add host
  import_playbook: host_add.yml 

- name: ssh copy id
  import_playbook: ssh_copy_id.yml 

- name: install language
  import_playbook: lang_install.yml 

- name: install timesync
  import_playbook: timesync_install.yml 
...