---
- hosts: all
  vars:
    home: "{{ lookup('env', 'HOME') }}"
    user: "{{ lookup('env', 'USER') }}"
    pri_key: "{{ home }}/.ssh/id_rsa"
  tasks:
  - name: debug
    debug:
      msg: >
        "home: {{ home }},
        user: {{ user }},
        pri_key: {{ pri_key }}"
    tags:
    - debug
  - name: /etc/sudoers
    become: yes
    lineinfile:
      path: "/etc/sudoers"
      line: "{{ user }} ALL=(ALL) NOPASSWD:ALL"
      validate: "/usr/sbin/visudo -cf %s"
  - name: /etc/hosts
    become: yes
    lineinfile:
      path: "/etc/hosts"
      line: "{{ hostvars[item].ansible_host }} {{ hostvars[item].inventory_hostname }}"
    with_items: "{{ groups['all'] }}"
  - name: openssh_keypair
    openssh_keypair:
      path: "{{ pri_key }}"
  - name: authorized_key
    vars:
      pub_key: "{{ lookup('file', '{{ home }}/.ssh/id_rsa.pub') }}"
    authorized_key:
      user: "{{ user }}"
      state: present
      key: "{{ pub_key }}"    

- name: install language
  import_playbook: lang_install.yml 

- name: install timesync
  import_playbook: timesync_install.yml 

...