---
- hosts: all
  vars:
    home: "{{ lookup('env', 'HOME') }}"
    user: "{{ lookup('env', 'USER') }}"
    pri_key: "{{ home }}/.ssh/id_rsa"
  tasks:
  - name: openssh_keypair
    openssh_keypair:
      path: "{{ pri_key }}"
  - name: authorized_key
    vars:
      pub_key: "{{ lookup('file', '{{ home }}/.ssh/id_rsa.pub') }}"
    authorized_key:
      user: "{{ user }}"
      state: present
      key: "{{ pub_key }}"    
      
...